version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10
    
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      - run: zip -r eutambem.zip .
      - persist_to_workspace:
          root: .
          paths:
            - eutambem.zip
  upload:
      docker:
        - image: circleci/python:2.7-jessie
      working_directory: ~/circleci-docs
      steps:
        - run:
            name: Install awscli
            command: sudo pip install awscli
        - attach_workspace:
            at: .
        - run:
            name: Upload to S3
            command: aws s3 cp eutambem.zip s3://eutambem-src/${CIRCLE_BUILD_NUM}/eutambem.zip
        - run:
            name: Trigger deployment pipeline (eutambem-serverless)
            command: 'curl -X POST -u $CIRCLE_CI_API_TOKEN: https://circleci.com/api/v1.1/project/github/eutambem/eutambem-serverless/build'


workflows:
  version: 2
  build-upload:
    jobs:
      - build
      - upload:
          requires:
            - build
          filters:
            branches:
              only: master

