version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10
    
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      - run: zip -r eutambem.zip .
      - persist_to_workspace:
          root: .
          paths:
            - eutambem.zip
  deploy:
      docker:
        - image: circleci/python:2.7-jessie
      working_directory: ~/circleci-docs
      steps:
        - run:
            name: Install awscli
            command: sudo pip install awscli
        - attach_workspace:
            at: .
        - run:
            name: Deploy to S3
            command: aws s3 cp eutambem.zip s3://eutambem-src/v0.0.1/eutambem.zip

  workflows:
    version: 2
    build-deploy:
      jobs:
        - build
        - deploy:
            requires:
              - build
            filters:
              branches:
                only: master

